[terminal.shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.9
blur = true

[font]
size = 11.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 1

[font.glyph_offset]
x = 0
y = 0

[colors.primary]
background = "#24283b"
foreground = "#c0caf5"

[colors.cursor]
text = "#24283b"
cursor = "#c0caf5"

[colors.selection]
background = "#364a82"
text = "#c0caf5"

[colors.normal]
black   = "#1d202f"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#a9b1d6"

[colors.bright]
black   = "#414868"
red     = "#f7768e"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#c0caf5"

[colors.dim]
black   = "#1d202f"
red     = "#db4b4b"
green   = "#9ece6a"
yellow  = "#e0af68"
blue    = "#7aa2f7"
magenta = "#bb9af7"
cyan    = "#7dcfff"
white   = "#828bb8"

[cursor]
style = "Block"
unfocused_hollow = true

[scrolling]
history = 10000
